In [1]:
import numpy as np

In [2]:
arr = [1,2,3,4,5]
np_arr = np.array(arr)
type(np_arr)

numpy.ndarray

In [3]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
# tablica 2D
arr2d = np.array([ [1,2,3,4,5] , [6,7,8,9,10], [11,12,13,14,15]  ])
arr2d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [5]:
arr = np.full( (3,4),  True)
arr

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [7]:
arr1 = np.arange(0,10)
arr2 = np.arange(-10,0)
print(arr1)
print(arr2)

[0 1 2 3 4 5 6 7 8 9]
[-10  -9  -8  -7  -6  -5  -4  -3  -2  -1]


In [8]:
arr1 + arr2

array([-10,  -8,  -6,  -4,  -2,   0,   2,   4,   6,   8])

In [9]:
arr1 * arr2

array([  0,  -9, -16, -21, -24, -25, -24, -21, -16,  -9])

In [10]:
arr1 / arr2

array([-0.        , -0.11111111, -0.25      , -0.42857143, -0.66666667,
       -1.        , -1.5       , -2.33333333, -4.        , -9.        ])

In [12]:
arr1 * 10.5

array([ 0. , 10.5, 21. , 31.5, 42. , 52.5, 63. , 73.5, 84. , 94.5])

In [18]:
# pobierz tylko parzyste
arr1 = np.arange(-10, 10)
condition = (arr1 % 2 == 0)
arr1[condition]

array([-10,  -8,  -6,  -4,  -2,   0,   2,   4,   6,   8])

In [30]:
# zastąp wartosci nieparzyste liczba -999
arr1 = np.array([0,1,2,3,4,5,6,7,8,9])
condition = (arr1 % 2 == 1)
arr1[condition] = -999
arr1

array([   0, -999,    2, -999,    4, -999,    6, -999,    8, -999])

In [32]:
# zastąp wartosci nieparzyste liczba -999
arr1 = np.array([0,1,2,3,4,5,6,7,8,9])
arr2 = np.where(arr1%2, arr1, -999)
arr2

array([-999,    1, -999,    3, -999,    5, -999,    7, -999,    9])

In [34]:
arr1 = np.arange(0,100)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [43]:
arr2 = arr1.reshape(20,-1)
arr2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84],
       [85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94],
       [95, 96, 97, 98, 99]])

In [44]:
arr1 = np.arange(0,10)
arr2 = np.arange(10,20)
arr3 = np.arange(20,30)
out = np.vstack([arr1, arr2, arr3])
out

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [45]:
out = np.hstack([arr1, arr2, arr3])
out

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [54]:
arr = np.array([ [0,1,2,3,4],[5,6,7,8,9], [10,11,12,13,14], [15,16,17,18,19], [20,21,22,23,24] ])
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [60]:
arr[::2, ::3]

array([[ 0,  3],
       [10, 13],
       [20, 23]])

In [64]:
arr[::-1, ::-1] #odwraca wiersze i kolumny

array([[24, 23, 22, 21, 20],
       [19, 18, 17, 16, 15],
       [14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])

In [72]:
# tablica z wartosciami pseudolosowymi
np.random.seed(123)
rand_arr = np.random.randint(-10, 10+1, [5,6])
(avg, median, std_dev) = np.mean(rand_arr), np.median(rand_arr), np.std(rand_arr)
print(avg, median, std_dev, sep=' , ') 

-0.5666666666666667 , -0.5 , 7.1539421921685165


In [73]:
np.percentile(rand_arr, q=[25,75])

array([-8.  ,  5.75])

In [78]:
arr = np.array([0,1,2,3,4,5, np.nan, 6, np.nan, 7, 8, np.nan])
np.isnan(arr).sum() #policz ile jest NaN

3